language: node_js
node_js:
  - 14

services:
  - docker

script:
  - npm run lint
  - npm run build
  - npm run coverage

after_script:
  - COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN npm run coveralls

cache:
  directories:
    - /node_modules

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master