language: node_js
node_js:
    - 14

services:
    - docker

script:
    - npm run coverage
    - npm run lint
    - npm run build

after_script:
    - COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN npm run coveralls

cache:
    directories:
        - /node_modules

deploy:
    provider: script
    script: bash docker_push.sh
    on:
        branch: master
